### ISSUE TITLE
MS 事前準備

### ISSUE THREAD

**Issue by yuhattor** [tbuchi888/cicd-handson#1]
@tbuchi888 追加あったら教えてください

## Task in Action
- [x] Codespaces の代わりに github.devや github.com の代わりに PAT でのshell experience も追加（手順移動）
- [x] 火曜日にリマインダー (GitHub, Docker 作成)
- [x] 3.5 以降の手順について確認
- [x] Docker はアクセストークンに変更
- [x] az aks create コマンドに Service Principal 関連の設定 Params を追加
- [x] 削除手順の追加 (Resource Group / AAD Service Principal / PAT)
- [x] GitHub アカウントは代表者が作り、自分で作業する感じで良いですかね？
- [x] ブレークアウトルームの作成
- [x] セッションの進行について Sync -> 戻ってくる流れ
- [x] 進め方、チームでの共同作業のやり方についてsync (おまかせする / 画面コントロール or Step ごとにわける)
- [x] ドライラン
